# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: Casey Huang
description: > # this means to ignore newlines until "email:"
   Visualization experiment playground

email: yh2726@@columbia.edu
#blog logo
logo: "/assets/images/IMG-20131210-WA0003.jpg"
# blog cover
cover: "/assets/images/283.jpg"

name: ‘Casey Huang’
author: ‘Casey Huang’
author_image: "/assets/images/IMG-20131210-WA0004.jpg"

paginate:	5

# url: "http://casey-huang.github.io” 

# social icons and sharing options
social:

  - icon:	github
    url:	https://github.com/casey-huang
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
